### ISSUE TITLE
Can't get the output for other test cases

### ISSUE THREAD

**Issue by MauricioRobayo** [Oluwadamilareolusakin/sliding-maximum-window-with-deque#3]
@Oluwadamilareolusakin: 💯 Great work!

Read [your article on Medium](https://medium.com/better-programming/solving-the-sliding-maximum-window-problem-with-o-n-b43ea3dd871f) and enjoy it a lot: very informative and well written 🥇 . Thanks for sharing your knowledge and your brilliant implementation.

Maybe you can point what am I missing when testing your code with the following input:

```ruby
p sliding_maximum(4, [10, 7, 1, 5, 3, 9])
# I think this should be the expected result: [10, 7, 9]
# This is the result I got: [10, 3, 9]

p sliding_maximum(4, [10, 7, 1, 5, 3, 9])
# I think this should be the expected result: [10, 7, 9]
# I got the following error: "undefined method `next_node' for nil:NilClass (NoMethodError)"
```

Thanks in advance for helping me understand what I might be getting wrong on those cases 😊.

**Comment by nikasulo** [comment]
Hey man! Thanks for your kind reply. Is it my exact code you're testing?

**Comment by nikasulo** [comment]
The two test cases are the same, how come they are giving you different results my friend?

**Comment by MauricioRobayo** [comment]
Sorry, this is the second one:

```ruby
p sliding_maximum(4, [9, 3, 5, 1, 12, 10])
```

**Comment by nikasulo** [comment]
Okay man, trying to resolve the issue rn. Thanks so much for pointing it out

**Comment by nikasulo** [comment]
I just tried the second case, it works

**Comment by MauricioRobayo** [comment]
Then I might be doing something wrong, keep getting this error:

```
/lib/deque.rb:21:in `popFront': undefined method `next_node' for nil:NilClass (NoMethodError)
```

**Comment by nikasulo** [comment]
The first test case fails truly, let me fix and push up

**Comment by MauricioRobayo** [comment]
Same for this one, same error: `p sliding_maximum(3, [8, 0, 4, 2, 0, 6, 4, 8, 5, 7])`

**Comment by nikasulo** [comment]
I've found the issue my friend

**Comment by nikasulo** [comment]
Hey my friend, so the issue was with the step that checks for potential maximums. Also I had to correct a few methods in the deque as they were also causing errors. You can check it out and let me know. I appreciate you pointing it out.

**Comment by MauricioRobayo** [comment]
@Oluwadamilareolusakin Awesome! 🚀 That's some beautiful code.

Maybe it's just me doing something wrong, but what should be the expected output for this case:

https://github.com/Oluwadamilareolusakin/sliding-maximum-window-with-deque/blob/43e8cbacb5533454eae775b024c555ee6e4cde70/main/sliding_maximum.rb#L69

I think I'm not getting the expected answer.

**Comment by nikasulo** [comment]
I'm about to push a fix for that. I noticed it right after my last comment
